[2022-10-29 22:08:31,173] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-29 22:08:31,179] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-29 22:08:31,179] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-29 22:08:31,179] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-29 22:08:31,179] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-29 22:08:31,187] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-29 22:08:31,192] {standard_task_runner.py:52} INFO - Started process 3204 to run task
[2022-10-29 22:08:31,194] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmp74h3fb_0', '--error-file', '/tmp/tmpx5mb3e4g']
[2022-10-29 22:08:31,195] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-29 22:08:31,327] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host 46fb15ce4cdf
[2022-10-29 22:08:31,373] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-29 22:08:31,373] {selenium_hook.py:15} INFO - initialised hook
[2022-10-29 22:08:31,373] {selenium_hook.py:19} INFO - getting ip
[2022-10-29 22:08:31,375] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/selenium_operator.py", line 22, in execute
    hook.get_ip_add()
  File "/opt/airflow/plugins/hooks/selenium_hook.py", line 20, in get_ip_add
    client = docker.DockerClient()
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 222, in _retrieve_server_version
    f'Error while fetching server API version: {e}'
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2022-10-29 22:08:31,380] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_denue, task_id=get_files, execution_date=20220901T000000, start_date=20221029T220831, end_date=20221029T220831
[2022-10-29 22:08:31,385] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task get_files (Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory')); 3204)
[2022-10-29 22:08:31,405] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-29 22:08:31,529] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-30 01:35:21,221] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 01:35:21,227] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 01:35:21,227] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 01:35:21,227] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 01:35:21,227] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 01:35:21,236] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 01:35:21,242] {standard_task_runner.py:52} INFO - Started process 256 to run task
[2022-10-30 01:35:21,244] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmpgblz6mem', '--error-file', '/tmp/tmpds7lpf9q']
[2022-10-30 01:35:21,244] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 01:35:21,391] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host 66fd04e3ce6d
[2022-10-30 01:35:21,443] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 01:35:21,443] {selenium_hook.py:15} INFO - initialised hook
[2022-10-30 01:35:21,443] {selenium_hook.py:19} INFO - getting ip
[2022-10-30 01:35:21,443] {selenium_hook.py:32} INFO - creating driver
[2022-10-30 01:37:31,237] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f4d2d9fd0>: Failed to establish a new connection: [Errno 110] Connection timed out')': /wd/hub/session
[2022-10-30 01:38:37,802] {local_task_job.py:221} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2022-10-30 01:38:37,804] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 256. PIDs of all processes in the group: [256]
[2022-10-30 01:38:37,804] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 256
[2022-10-30 01:38:37,804] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-30 01:38:37,804] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 01:39:29,870] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-30 01:39:29,871] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 256. PIDs of all processes in the group: [256]
[2022-10-30 01:39:29,873] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 256
[2022-10-30 01:39:29,873] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-30 01:39:29,873] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 01:41:00,966] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 01:41:00,973] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 01:41:00,973] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 01:41:00,973] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 01:41:00,973] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 01:41:00,984] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 01:41:00,990] {standard_task_runner.py:52} INFO - Started process 258 to run task
[2022-10-30 01:41:00,992] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmptyvnfsuu', '--error-file', '/tmp/tmphcjdqcme']
[2022-10-30 01:41:00,993] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 01:41:01,030] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host 5499b66c80f9
[2022-10-30 01:41:01,189] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 01:41:01,189] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 01:41:01,189] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 01:41:01,189] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 01:43:11,205] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34dc5f3d90>: Failed to establish a new connection: [Errno 110] Connection timed out')': /wd/hub/session
[2022-10-30 01:45:22,277] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34dc602890>: Failed to establish a new connection: [Errno 110] Connection timed out')': /wd/hub/session
[2022-10-30 01:47:33,349] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34dc602f50>: Failed to establish a new connection: [Errno 110] Connection timed out')': /wd/hub/session
[2022-10-30 01:49:44,421] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 01:51:59,589] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34dc6027d0>: Failed to establish a new connection: [Errno 110] Connection timed out')': /wd/hub/session
[2022-10-30 01:54:10,661] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34dc5f1710>: Failed to establish a new connection: [Errno 110] Connection timed out')': /wd/hub/session
[2022-10-30 01:56:21,733] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34dc82c390>: Failed to establish a new connection: [Errno 110] Connection timed out')': /wd/hub/session
[2022-10-30 01:58:32,805] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:00:47,973] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34dc632a10>: Failed to establish a new connection: [Errno 110] Connection timed out')': /wd/hub/session
[2022-10-30 02:02:59,045] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34dc632d50>: Failed to establish a new connection: [Errno 110] Connection timed out')': /wd/hub/session
[2022-10-30 02:05:10,117] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34dc6fc110>: Failed to establish a new connection: [Errno 110] Connection timed out')': /wd/hub/session
[2022-10-30 02:07:21,189] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:08:26,926] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-30 02:08:26,928] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 258. PIDs of all processes in the group: [258]
[2022-10-30 02:08:26,928] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 258
[2022-10-30 02:08:26,928] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-30 02:08:26,928] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:26:08,522] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 02:26:08,527] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 02:26:08,527] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 02:26:08,527] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 02:26:08,527] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 02:26:08,535] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 02:26:08,541] {standard_task_runner.py:52} INFO - Started process 255 to run task
[2022-10-30 02:26:08,542] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmp_y3oarec', '--error-file', '/tmp/tmpzhjz0h9_']
[2022-10-30 02:26:08,543] {standard_task_runner.py:80} INFO - Job 5: Subtask get_files
[2022-10-30 02:26:08,576] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host 11c07e039b5e
[2022-10-30 02:26:08,723] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 02:26:08,724] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 02:26:08,724] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 02:26:08,724] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 02:27:09,030] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-30 02:27:09,031] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 255. PIDs of all processes in the group: [255]
[2022-10-30 02:27:09,032] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 255
[2022-10-30 02:27:09,032] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-30 02:27:09,032] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:28:27,277] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 02:28:27,283] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 02:28:27,283] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 02:28:27,283] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 02:28:27,284] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 02:28:27,291] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 02:28:27,297] {standard_task_runner.py:52} INFO - Started process 212 to run task
[2022-10-30 02:28:27,299] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmpftkc9vxg', '--error-file', '/tmp/tmp_tb0jsy2']
[2022-10-30 02:28:27,300] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 02:28:27,333] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host 69ae14f7db93
[2022-10-30 02:28:27,481] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 02:28:27,482] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 02:28:27,482] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 02:28:27,482] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 02:28:30,537] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9e9fd0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:28:33,605] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9f8890>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:28:36,677] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fda28090>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:28:39,749] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:28:47,813] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9f8810>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:28:50,885] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9e96d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:28:53,957] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9e71d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:28:57,033] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:29:05,097] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fda28ad0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:29:08,165] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fda28e10>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:29:11,237] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf2190>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:29:14,309] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:29:22,373] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf2c10>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:29:25,445] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf2f50>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:29:28,517] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafc2d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:29:31,589] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:29:39,656] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf2e90>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:29:42,725] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf26d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:29:45,797] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf2510>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:29:48,869] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:29:56,933] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9e90d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:30:00,005] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9f86d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:30:03,080] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9f8850>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:30:06,149] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:30:14,216] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafcc10>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:30:17,285] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafcf50>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:30:20,357] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb042d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:30:23,429] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:30:31,493] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb04d50>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:30:34,565] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb07110>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:30:37,637] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb07410>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:30:40,709] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:30:48,773] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9f8910>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:30:51,845] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9b2a90>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:30:54,917] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9e96d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:30:57,989] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:31:06,053] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafc450>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:31:09,125] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafc610>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:31:12,196] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafc850>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:31:15,269] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:31:23,332] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb07d50>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:31:26,404] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf2dd0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:31:29,477] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf2490>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:31:32,549] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:31:40,613] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdd0a8d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:31:43,689] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafc6d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:31:46,757] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafc990>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:31:49,829] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:31:57,893] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9e74d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:32:00,965] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9e9e90>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:32:04,036] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9f8a10>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:32:07,109] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:32:15,173] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb07a90>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:32:18,245] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb07710>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:32:21,317] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb04f50>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:32:24,389] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:32:32,453] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf2390>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:32:35,525] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf2b90>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:32:38,597] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf2c10>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:32:41,669] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:32:49,733] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9f88d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:32:52,805] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9f8890>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:32:55,877] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9e96d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:32:58,948] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:33:07,013] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb07a90>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:33:10,089] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb07e10>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:33:13,157] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf2cd0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:33:16,229] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:33:24,293] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafcd10>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:33:27,365] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafc1d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:33:30,437] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafca10>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:33:33,509] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:33:41,573] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb13a50>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:33:44,645] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb13d90>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:33:47,717] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafc850>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:33:50,789] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:33:58,853] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafcd50>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:34:01,925] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf2550>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:34:04,996] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf2510>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:34:08,069] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:34:16,133] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb07810>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:34:19,205] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb07d50>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:34:22,277] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9e9c50>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:34:25,349] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:34:33,413] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb04290>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:34:36,485] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb044d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:34:39,557] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb131d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:34:42,629] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:34:50,693] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb04090>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:34:53,765] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9f8cd0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:34:56,837] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9f8650>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:34:59,909] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:35:07,973] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb078d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:35:11,045] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb07f10>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:35:14,117] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb074d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:35:17,189] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:35:25,253] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafc250>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:35:28,325] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafced0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:35:31,397] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafc710>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:35:34,469] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:35:42,533] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb13e50>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:35:45,605] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb1b110>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:35:48,677] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb1b710>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:35:51,749] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:35:59,813] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafc8d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:36:02,885] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdafcf50>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:36:05,957] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdaf2b50>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:36:09,033] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:36:17,093] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb076d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:36:20,169] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb07550>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:36:23,237] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb075d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:36:26,309] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:36:34,373] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9b2c10>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:36:37,445] {connectionpool.py:811} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9f8950>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:36:40,517] {connectionpool.py:811} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fd9f8810>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:36:43,589] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:36:51,653] {connectionpool.py:811} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc3fdb251d0>: Failed to establish a new connection: [Errno 113] No route to host')': /wd/hub/session
[2022-10-30 02:36:52,061] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-30 02:36:52,063] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 212. PIDs of all processes in the group: [212]
[2022-10-30 02:36:52,063] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 212
[2022-10-30 02:36:52,063] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-30 02:36:52,063] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:39:20,923] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 02:39:20,929] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 02:39:20,929] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 02:39:20,929] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 02:39:20,929] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 02:39:20,937] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 02:39:20,943] {standard_task_runner.py:52} INFO - Started process 323 to run task
[2022-10-30 02:39:20,945] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmpoyt96iyj', '--error-file', '/tmp/tmp8sfrsflq']
[2022-10-30 02:39:20,946] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 02:39:20,979] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host 5cd8a46fae14
[2022-10-30 02:39:21,123] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 02:39:21,124] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 02:39:21,124] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 02:39:21,124] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 02:41:06,820] {local_task_job.py:221} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2022-10-30 02:41:06,822] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 323. PIDs of all processes in the group: [323]
[2022-10-30 02:41:06,822] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 323
[2022-10-30 02:41:06,822] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-30 02:41:06,822] {selenium_hook.py:45} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 02:42:06,838] {process_utils.py:143} WARNING - process psutil.Process(pid=323, name='airflow task ru', status='sleeping', started='02:39:20') did not respond to SIGTERM. Trying SIGKILL
[2022-10-30 02:42:06,839] {process_utils.py:80} INFO - Sending the signal Signals.SIGKILL to group 323
[2022-10-30 02:42:06,852] {process_utils.py:75} INFO - Process psutil.Process(pid=323, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='02:39:20') (323) terminated with exit code Negsignal.SIGKILL
[2022-10-30 02:42:06,852] {standard_task_runner.py:162} ERROR - Job 3 was killed before it finished (likely due to running out of memory)
[2022-10-30 03:04:53,240] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 03:04:53,246] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 03:04:53,246] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 03:04:53,246] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 03:04:53,246] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 03:04:53,253] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 03:04:53,259] {standard_task_runner.py:52} INFO - Started process 239 to run task
[2022-10-30 03:04:53,260] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmp8xr2cc_a', '--error-file', '/tmp/tmp80sjj5fz']
[2022-10-30 03:04:53,261] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 03:04:53,294] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host d0b9aa827c7b
[2022-10-30 03:04:53,442] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 03:04:53,443] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 03:04:53,443] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 03:04:53,443] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 03:04:53,443] {selenium_hook.py:32} INFO - localhost
[2022-10-30 03:04:53,443] {selenium_hook.py:37} INFO - localhost:4444/
[2022-10-30 03:04:53,443] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:05:03,453] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:05:13,457] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:05:23,465] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:05:33,475] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:05:43,486] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:05:53,488] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:06:03,497] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:06:13,498] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:06:23,505] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:06:33,515] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:06:43,525] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:06:53,533] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:07:03,541] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:07:13,551] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:07:23,562] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:07:33,569] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:07:43,577] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:07:53,585] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:08:03,596] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:08:13,605] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:08:23,615] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:08:33,624] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:08:43,633] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:08:53,641] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:09:03,651] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:09:13,661] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:09:23,671] {selenium_hook.py:47} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:09:28,999] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-30 03:09:29,001] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 239. PIDs of all processes in the group: [239]
[2022-10-30 03:09:29,001] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 239
[2022-10-30 03:09:29,001] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-30 03:09:29,013] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/hooks/selenium_hook.py", line 43, in create_driver
    options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 427, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 344, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 366, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 365, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 237, in connection_from_host
    raise LocationValueError("No host specified.")
urllib3.exceptions.LocationValueError: No host specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/selenium_operator.py", line 23, in execute
    hook.create_driver()
  File "/opt/airflow/plugins/hooks/selenium_hook.py", line 48, in create_driver
    logging.info('remote not ready, sleeping for ten seconds')
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1563, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-10-30 03:09:29,017] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_denue, task_id=get_files, execution_date=20220901T000000, start_date=20221030T030453, end_date=20221030T030929
[2022-10-30 03:09:29,035] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task get_files (Task received SIGTERM signal; 239)
[2022-10-30 03:09:29,055] {process_utils.py:75} INFO - Process psutil.Process(pid=239, status='terminated', exitcode=1, started='03:04:53') (239) terminated with exit code 1
[2022-10-30 03:09:29,056] {local_task_job.py:156} INFO - Task exited with return code 143
[2022-10-30 03:09:29,086] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-30 03:11:41,618] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 03:11:41,626] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 03:11:41,626] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 03:11:41,626] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 03:11:41,626] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 03:11:41,638] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 03:11:41,644] {standard_task_runner.py:52} INFO - Started process 212 to run task
[2022-10-30 03:11:41,646] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmpweyv1ip4', '--error-file', '/tmp/tmph14gra9k']
[2022-10-30 03:11:41,647] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 03:11:41,686] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host 007ff0dcadd8
[2022-10-30 03:11:41,847] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 03:11:41,847] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 03:11:41,847] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 03:11:41,847] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 03:11:41,847] {selenium_hook.py:32} INFO - localhost
[2022-10-30 03:11:41,847] {selenium_hook.py:37} INFO - localhost:4444/
[2022-10-30 03:11:41,848] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:11:41,848] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:11:51,850] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:11:51,850] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:12:01,861] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:12:01,861] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:12:11,869] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:12:11,869] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:12:21,877] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:12:21,877] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:12:31,885] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:12:31,885] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:12:41,893] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:12:41,893] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:12:51,903] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:12:51,903] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:13:01,904] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:13:01,904] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:13:11,915] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:13:11,915] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:13:21,925] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:13:21,925] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:13:31,935] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:13:31,935] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:13:41,945] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:13:41,945] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:13:51,951] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:13:51,951] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:14:01,961] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:14:01,961] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:14:11,969] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:14:11,969] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:14:21,980] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:14:21,980] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:14:31,989] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:14:31,989] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:14:41,999] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:14:41,999] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:14:52,010] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:14:52,010] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:15:02,021] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:15:02,021] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:15:12,031] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:15:12,031] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:15:22,037] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:15:22,037] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:15:32,047] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:15:32,048] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:15:42,057] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:15:42,057] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:15:52,067] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:15:52,067] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:16:02,078] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:16:02,078] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:16:12,081] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:16:12,081] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:16:22,089] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:16:22,089] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:16:32,099] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:16:32,099] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:16:42,109] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:16:42,109] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:16:52,117] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:16:52,117] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:17:02,127] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:17:02,128] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:17:12,138] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:17:12,138] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:17:22,149] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:17:22,149] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:17:32,159] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:17:32,159] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:17:42,169] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:17:42,169] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:17:52,177] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:17:52,177] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:18:02,185] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:18:02,185] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:18:12,193] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:18:12,193] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:18:22,204] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:18:22,204] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:18:32,213] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:18:32,213] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:18:42,221] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:18:42,221] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:18:52,229] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:18:52,229] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:19:02,239] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:19:02,239] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:19:12,249] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:19:12,249] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:19:22,257] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:19:22,257] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:19:32,261] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:19:32,261] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:19:42,269] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:19:42,269] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:19:52,279] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:19:52,279] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:20:02,289] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:20:02,289] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:20:12,299] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:20:12,300] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:20:22,310] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:20:22,310] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:20:32,317] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:20:32,317] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:20:42,325] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:20:42,325] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:20:52,328] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:20:52,328] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:21:02,339] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:21:02,339] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:21:12,342] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:21:12,342] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:21:22,353] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:21:22,353] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:21:32,363] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:21:32,363] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:21:42,367] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:21:42,368] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:21:52,377] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:21:52,377] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:22:02,385] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:22:02,385] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:22:12,395] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:22:12,396] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:22:22,405] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:22:22,405] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:22:32,414] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:22:32,414] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:22:42,421] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:22:42,421] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:22:52,425] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:22:52,425] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:23:02,433] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:23:02,433] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:23:12,441] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:23:12,441] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:23:22,451] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:23:22,451] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:23:32,461] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:23:32,461] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:23:42,471] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:23:42,471] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:23:52,481] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:23:52,481] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:24:02,491] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:24:02,491] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:24:12,501] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:24:12,501] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:24:22,511] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:24:22,511] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:24:32,521] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:24:32,521] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:24:42,529] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:24:42,529] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:24:52,539] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:24:52,539] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:25:02,549] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:25:02,549] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:25:12,559] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:25:12,559] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:25:22,570] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:25:22,570] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:25:32,577] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:25:32,577] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:25:42,585] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:25:42,585] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:25:52,592] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:25:52,592] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:26:02,601] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:26:02,601] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:26:12,609] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:26:12,609] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:26:22,619] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:26:22,619] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:26:32,630] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:26:32,630] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:26:42,637] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:26:42,637] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:26:52,647] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:26:52,648] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:27:02,658] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:27:02,658] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:27:12,669] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:27:12,669] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:27:22,677] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:27:22,678] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:27:32,681] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:27:32,682] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:27:42,689] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:27:42,689] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:27:52,697] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:27:52,697] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:28:02,705] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:28:02,705] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:28:12,713] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:28:12,713] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:28:22,721] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:28:22,721] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:28:32,729] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:28:32,729] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:28:42,737] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:28:42,737] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:28:52,747] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:28:52,747] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:29:02,757] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:29:02,757] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:29:12,765] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:29:12,765] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:29:22,773] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:29:22,773] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:29:32,783] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:29:32,783] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:29:42,793] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:29:42,793] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:29:52,797] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:29:52,797] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:30:02,805] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:30:02,805] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:30:12,813] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:30:12,813] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:30:22,821] {selenium_hook.py:47} ERROR - No host specified.
[2022-10-30 03:30:22,821] {selenium_hook.py:48} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:30:24,458] {local_task_job.py:221} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2022-10-30 03:30:24,460] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 212. PIDs of all processes in the group: [212]
[2022-10-30 03:30:24,460] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 212
[2022-10-30 03:30:24,460] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-30 03:30:24,468] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/hooks/selenium_hook.py", line 43, in create_driver
    options=options)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 427, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 344, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 366, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 365, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 237, in connection_from_host
    raise LocationValueError("No host specified.")
urllib3.exceptions.LocationValueError: No host specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/selenium_operator.py", line 23, in execute
    hook.create_driver()
  File "/opt/airflow/plugins/hooks/selenium_hook.py", line 49, in create_driver
    time.sleep(10)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1563, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-10-30 03:30:24,470] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_denue, task_id=get_files, execution_date=20220901T000000, start_date=20221030T031141, end_date=20221030T033024
[2022-10-30 03:30:24,477] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task get_files (Task received SIGTERM signal; 212)
[2022-10-30 03:30:24,512] {process_utils.py:75} INFO - Process psutil.Process(pid=212, status='terminated', exitcode=1, started='03:11:41') (212) terminated with exit code 1
[2022-10-30 03:50:38,247] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 03:50:38,252] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 03:50:38,252] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 03:50:38,252] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 03:50:38,252] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 03:50:38,260] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 03:50:38,266] {standard_task_runner.py:52} INFO - Started process 212 to run task
[2022-10-30 03:50:38,268] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmp9jd4hcvb', '--error-file', '/tmp/tmp6_ms9w5p']
[2022-10-30 03:50:38,269] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 03:50:38,303] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host d657203aed06
[2022-10-30 03:50:38,450] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 03:50:38,450] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 03:50:38,450] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 03:50:38,450] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 03:55:38,488] {selenium_hook.py:49} ERROR - Message: Could not start a new session. New session request timed out 
Host info: host: 'c71bf6845b75', ip: '10.5.0.5'
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-52-generic', java.version: '11.0.16'
Driver info: driver.version: unknown
Stacktrace:
    at org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue.addToQueue (LocalNewSessionQueue.java:202)
    at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0 (NewSessionQueue.java:69)
    at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle (Route.java:192)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute (NewSessionQueue.java:123)
    at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute (SpanWrappedHttpHandler.java:86)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.grid.router.Router.execute (Router.java:91)
    at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0 (EnsureSpecCompliantResponseHeaders.java:34)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.http.Route$NestedRoute.handle (Route.java:270)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0 (AddWebDriverSpecHeaders.java:35)
    at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0 (SeleniumHandler.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
[2022-10-30 03:55:38,488] {selenium_hook.py:50} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:58:41,824] {local_task_job.py:221} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2022-10-30 03:58:41,826] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 212. PIDs of all processes in the group: [212]
[2022-10-30 03:58:41,826] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 212
[2022-10-30 03:58:41,826] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-30 03:58:41,826] {selenium_hook.py:49} ERROR - Task received SIGTERM signal
[2022-10-30 03:58:41,826] {selenium_hook.py:50} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 03:59:41,862] {process_utils.py:143} WARNING - process psutil.Process(pid=212, name='airflow task ru', status='sleeping', started='03:50:38') did not respond to SIGTERM. Trying SIGKILL
[2022-10-30 03:59:41,862] {process_utils.py:80} INFO - Sending the signal Signals.SIGKILL to group 212
[2022-10-30 03:59:41,876] {process_utils.py:75} INFO - Process psutil.Process(pid=212, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='03:50:38') (212) terminated with exit code Negsignal.SIGKILL
[2022-10-30 03:59:41,876] {standard_task_runner.py:162} ERROR - Job 3 was killed before it finished (likely due to running out of memory)
[2022-10-30 04:07:15,206] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 04:07:15,213] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 04:07:15,213] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 04:07:15,213] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 04:07:15,213] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 04:07:15,222] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 04:07:15,227] {standard_task_runner.py:52} INFO - Started process 221 to run task
[2022-10-30 04:07:15,230] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmpeoepu297', '--error-file', '/tmp/tmpk5c_jtki']
[2022-10-30 04:07:15,231] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 04:07:15,273] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host c452f12643b9
[2022-10-30 04:07:15,445] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 04:07:15,446] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 04:07:15,446] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 04:07:15,446] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 04:12:15,479] {selenium_hook.py:49} ERROR - Message: Could not start a new session. New session request timed out 
Host info: host: '1c000c40e09a', ip: '10.5.0.5'
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-52-generic', java.version: '11.0.16'
Driver info: driver.version: unknown
Stacktrace:
    at org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue.addToQueue (LocalNewSessionQueue.java:202)
    at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0 (NewSessionQueue.java:69)
    at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle (Route.java:192)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute (NewSessionQueue.java:123)
    at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute (SpanWrappedHttpHandler.java:86)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.grid.router.Router.execute (Router.java:91)
    at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0 (EnsureSpecCompliantResponseHeaders.java:34)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0 (AddWebDriverSpecHeaders.java:35)
    at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0 (SeleniumHandler.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
[2022-10-30 04:12:15,479] {selenium_hook.py:50} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 04:17:25,498] {selenium_hook.py:49} ERROR - Message: Could not start a new session. New session request timed out 
Host info: host: '1c000c40e09a', ip: '10.5.0.5'
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-52-generic', java.version: '11.0.16'
Driver info: driver.version: unknown
Stacktrace:
    at org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue.addToQueue (LocalNewSessionQueue.java:202)
    at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0 (NewSessionQueue.java:69)
    at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle (Route.java:192)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute (NewSessionQueue.java:123)
    at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute (SpanWrappedHttpHandler.java:86)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.grid.router.Router.execute (Router.java:91)
    at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0 (EnsureSpecCompliantResponseHeaders.java:34)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0 (AddWebDriverSpecHeaders.java:35)
    at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0 (SeleniumHandler.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
[2022-10-30 04:17:25,498] {selenium_hook.py:50} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 04:22:35,518] {selenium_hook.py:49} ERROR - Message: Could not start a new session. New session request timed out 
Host info: host: '1c000c40e09a', ip: '10.5.0.5'
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-52-generic', java.version: '11.0.16'
Driver info: driver.version: unknown
Stacktrace:
    at org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue.addToQueue (LocalNewSessionQueue.java:202)
    at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0 (NewSessionQueue.java:69)
    at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle (Route.java:192)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute (NewSessionQueue.java:123)
    at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute (SpanWrappedHttpHandler.java:86)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.grid.router.Router.execute (Router.java:91)
    at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0 (EnsureSpecCompliantResponseHeaders.java:34)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0 (AddWebDriverSpecHeaders.java:35)
    at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0 (SeleniumHandler.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
[2022-10-30 04:22:35,518] {selenium_hook.py:50} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 04:27:45,539] {selenium_hook.py:49} ERROR - Message: Could not start a new session. New session request timed out 
Host info: host: '1c000c40e09a', ip: '10.5.0.5'
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-52-generic', java.version: '11.0.16'
Driver info: driver.version: unknown
Stacktrace:
    at org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue.addToQueue (LocalNewSessionQueue.java:202)
    at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0 (NewSessionQueue.java:69)
    at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle (Route.java:192)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute (NewSessionQueue.java:123)
    at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute (SpanWrappedHttpHandler.java:86)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.grid.router.Router.execute (Router.java:91)
    at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0 (EnsureSpecCompliantResponseHeaders.java:34)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:336)
    at org.openqa.selenium.remote.http.Route.execute (Route.java:68)
    at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0 (AddWebDriverSpecHeaders.java:35)
    at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)
    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:64)
    at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0 (SeleniumHandler.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:829)
[2022-10-30 04:27:45,539] {selenium_hook.py:50} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 04:28:11,652] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-30 04:28:11,654] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 221. PIDs of all processes in the group: [221]
[2022-10-30 04:28:11,654] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 221
[2022-10-30 04:28:11,654] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-30 04:28:11,654] {selenium_hook.py:49} ERROR - Task received SIGTERM signal
[2022-10-30 04:28:11,654] {selenium_hook.py:50} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 04:36:17,801] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 04:36:17,807] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 04:36:17,807] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 04:36:17,807] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 04:36:17,807] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 04:36:17,815] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 04:36:17,820] {standard_task_runner.py:52} INFO - Started process 237 to run task
[2022-10-30 04:36:17,822] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmpj61baavf', '--error-file', '/tmp/tmpayuir_gq']
[2022-10-30 04:36:17,823] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 04:36:17,863] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host a914f076f3c2
[2022-10-30 04:36:18,024] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 04:36:18,025] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 04:36:18,025] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 04:36:18,025] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 04:37:48,457] {local_task_job.py:221} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2022-10-30 04:37:48,458] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 237. PIDs of all processes in the group: [237]
[2022-10-30 04:37:48,458] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 237
[2022-10-30 04:37:48,458] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-30 04:37:48,458] {selenium_hook.py:49} ERROR - Task received SIGTERM signal
[2022-10-30 04:37:48,458] {selenium_hook.py:50} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 04:38:48,474] {process_utils.py:143} WARNING - process psutil.Process(pid=237, name='airflow task ru', status='sleeping', started='04:36:17') did not respond to SIGTERM. Trying SIGKILL
[2022-10-30 04:38:48,475] {process_utils.py:80} INFO - Sending the signal Signals.SIGKILL to group 237
[2022-10-30 04:38:48,488] {process_utils.py:75} INFO - Process psutil.Process(pid=237, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='04:36:17') (237) terminated with exit code Negsignal.SIGKILL
[2022-10-30 04:38:48,488] {standard_task_runner.py:162} ERROR - Job 3 was killed before it finished (likely due to running out of memory)
[2022-10-30 04:46:57,581] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 04:46:57,586] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 04:46:57,586] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 04:46:57,586] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 04:46:57,586] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 04:46:57,594] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 04:46:57,599] {standard_task_runner.py:52} INFO - Started process 238 to run task
[2022-10-30 04:46:57,601] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmpi9r5vmba', '--error-file', '/tmp/tmpsep0yp96']
[2022-10-30 04:46:57,602] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 04:46:57,636] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host 15625cd3b35e
[2022-10-30 04:46:57,786] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 04:46:57,787] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 04:46:57,787] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 04:46:57,787] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 04:48:13,144] {local_task_job.py:221} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2022-10-30 04:48:13,145] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 238. PIDs of all processes in the group: [238]
[2022-10-30 04:48:13,145] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 238
[2022-10-30 04:48:13,146] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-10-30 04:48:13,146] {selenium_hook.py:49} ERROR - Task received SIGTERM signal
[2022-10-30 04:48:13,146] {selenium_hook.py:50} INFO - remote not ready, sleeping for ten seconds
[2022-10-30 04:49:13,169] {process_utils.py:143} WARNING - process psutil.Process(pid=238, name='airflow task ru', status='sleeping', started='04:46:57') did not respond to SIGTERM. Trying SIGKILL
[2022-10-30 04:49:13,170] {process_utils.py:80} INFO - Sending the signal Signals.SIGKILL to group 238
[2022-10-30 04:49:13,183] {process_utils.py:75} INFO - Process psutil.Process(pid=238, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='04:46:57') (238) terminated with exit code Negsignal.SIGKILL
[2022-10-30 04:49:13,183] {standard_task_runner.py:162} ERROR - Job 3 was killed before it finished (likely due to running out of memory)
[2022-10-30 04:59:48,302] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 04:59:48,307] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 04:59:48,307] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 04:59:48,307] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 04:59:48,307] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 04:59:48,315] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 04:59:48,320] {standard_task_runner.py:52} INFO - Started process 212 to run task
[2022-10-30 04:59:48,322] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmpq_ckon1t', '--error-file', '/tmp/tmpuv7mt4j0']
[2022-10-30 04:59:48,323] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 04:59:48,355] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host b121f8e26b3b
[2022-10-30 04:59:48,501] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 04:59:48,501] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 04:59:48,501] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 04:59:48,501] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 04:59:48,843] {selenium_hook.py:46} INFO - remote ready
[2022-10-30 04:59:51,090] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/selenium_operator.py", line 24, in execute
    hook.run_script(self.script, self.script_args)
  File "/opt/airflow/plugins/hooks/selenium_hook.py", line 56, in run_script
    script(self.driver, *args)
  File "/opt/airflow/dags/utils/get_files.py", line 23, in selenium_scrapper
    soup = BeautifulSoup(page.content, 'html.parser')
AttributeError: 'NoneType' object has no attribute 'content'
[2022-10-30 04:59:51,096] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_denue, task_id=get_files, execution_date=20220901T000000, start_date=20221030T045948, end_date=20221030T045951
[2022-10-30 04:59:51,104] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task get_files ('NoneType' object has no attribute 'content'; 212)
[2022-10-30 04:59:51,138] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-30 04:59:51,163] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-30 05:03:13,160] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 05:03:13,166] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 05:03:13,166] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 05:03:13,166] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 05:03:13,166] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 05:03:13,174] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 05:03:13,179] {standard_task_runner.py:52} INFO - Started process 239 to run task
[2022-10-30 05:03:13,181] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmpnwf92aw1', '--error-file', '/tmp/tmpppkn87s6']
[2022-10-30 05:03:13,182] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 05:03:13,214] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host 35d711a1e0f4
[2022-10-30 05:03:13,362] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 05:03:13,362] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 05:03:13,362] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 05:03:13,362] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 05:03:13,722] {selenium_hook.py:46} INFO - remote ready
[2022-10-30 05:03:15,906] {logging_mixin.py:115} INFO - None
[2022-10-30 05:03:16,009] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=etl_denue, task_id=get_files, execution_date=20220901T000000, start_date=20221030T050313, end_date=20221030T050316
[2022-10-30 05:03:16,037] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-30 05:03:16,060] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-30 05:17:25,547] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 05:17:25,553] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 05:17:25,553] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 05:17:25,553] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 05:17:25,553] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 05:17:25,561] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 05:17:25,566] {standard_task_runner.py:52} INFO - Started process 203 to run task
[2022-10-30 05:17:25,568] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmpl__gqvt8', '--error-file', '/tmp/tmp7npdrzkf']
[2022-10-30 05:17:25,569] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 05:17:25,602] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host aa62e71d0153
[2022-10-30 05:17:25,749] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 05:17:25,750] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 05:17:25,750] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 05:17:25,750] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 05:17:26,085] {selenium_hook.py:46} INFO - remote ready
[2022-10-30 05:17:26,085] {logging_mixin.py:115} INFO - https://www.inegi.org.mx/app/descarga/?ti=6
[2022-10-30 05:17:38,259] {logging_mixin.py:115} INFO - None
[2022-10-30 05:17:38,346] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=etl_denue, task_id=get_files, execution_date=20220901T000000, start_date=20221030T051725, end_date=20221030T051738
[2022-10-30 05:17:38,380] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-30 05:17:38,398] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-30 05:42:25,357] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 05:42:25,363] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 05:42:25,363] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 05:42:25,363] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 05:42:25,363] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 05:42:25,371] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 05:42:25,376] {standard_task_runner.py:52} INFO - Started process 221 to run task
[2022-10-30 05:42:25,378] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmpleasdyoe', '--error-file', '/tmp/tmpyu87g4qf']
[2022-10-30 05:42:25,379] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 05:42:25,412] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host 0fc627f2f1f0
[2022-10-30 05:42:25,556] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 05:42:25,556] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 05:42:25,557] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 05:42:25,557] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 05:42:25,897] {selenium_hook.py:46} INFO - remote ready
[2022-10-30 05:42:25,898] {logging_mixin.py:115} INFO - https://www.inegi.org.mx/app/descarga/
[2022-10-30 05:42:28,309] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/selenium_operator.py", line 24, in execute
    hook.run_script(self.script, self.script_args)
  File "/opt/airflow/plugins/hooks/selenium_hook.py", line 56, in run_script
    script(self.driver, *args)
  File "/opt/airflow/dags/utils/get_files.py", line 26, in selenium_scrapper
    elem = driver.find_element_by_id("tblDescargaArchivos_denue")
AttributeError: 'WebDriver' object has no attribute 'find_element_by_id'
[2022-10-30 05:42:28,314] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_denue, task_id=get_files, execution_date=20220901T000000, start_date=20221030T054225, end_date=20221030T054228
[2022-10-30 05:42:28,321] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task get_files ('WebDriver' object has no attribute 'find_element_by_id'; 221)
[2022-10-30 05:42:28,355] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-30 05:42:28,379] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-30 05:45:44,942] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 05:45:44,947] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 05:45:44,948] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 05:45:44,948] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 05:45:44,948] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 05:45:44,955] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 05:45:44,961] {standard_task_runner.py:52} INFO - Started process 293 to run task
[2022-10-30 05:45:44,963] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmp_s2km7yg', '--error-file', '/tmp/tmpxy4zkfuc']
[2022-10-30 05:45:44,963] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 05:45:44,996] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host f80d6ee97b6d
[2022-10-30 05:45:45,139] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 05:45:45,139] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 05:45:45,140] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 05:45:45,140] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 05:45:45,561] {selenium_hook.py:46} INFO - remote ready
[2022-10-30 05:45:45,561] {logging_mixin.py:115} INFO - https://www.inegi.org.mx/app/descarga/
[2022-10-30 05:46:34,954] {logging_mixin.py:115} INFO - 'WebDriver' object has no attribute 'find_element_by_id'
[2022-10-30 05:46:35,034] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/selenium_operator.py", line 25, in execute
    hook.quit_driver()
  File "/opt/airflow/plugins/hooks/selenium_hook.py", line 60, in quit_driver
    self.driver.quit()
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 563, in quit
    self.execute(Command.QUIT)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: Unable to execute request for an existing session: Unable to find session with ID: 74bc8ee78f7d820d5f1e0b2e445a7d4e
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-52-generic', java.version: '11.0.16'
Driver info: driver.version: unknown

[2022-10-30 05:46:35,041] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_denue, task_id=get_files, execution_date=20220901T000000, start_date=20221030T054544, end_date=20221030T054635
[2022-10-30 05:46:35,048] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task get_files (Message: Unable to execute request for an existing session: Unable to find session with ID: 74bc8ee78f7d820d5f1e0b2e445a7d4e
Build info: version: '4.5.3', revision: '4b786a1e430'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-52-generic', java.version: '11.0.16'
Driver info: driver.version: unknown
; 293)
[2022-10-30 05:46:35,097] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-30 05:46:35,119] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-30 06:00:07,383] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 06:00:07,388] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 06:00:07,388] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 06:00:07,388] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 06:00:07,388] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 06:00:07,396] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 06:00:07,401] {standard_task_runner.py:52} INFO - Started process 239 to run task
[2022-10-30 06:00:07,403] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmpbpmim06l', '--error-file', '/tmp/tmpd4sj_ap3']
[2022-10-30 06:00:07,404] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 06:00:07,440] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host 1dd15365b03f
[2022-10-30 06:00:07,586] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 06:00:07,586] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 06:00:07,586] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 06:00:07,586] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 06:00:07,922] {selenium_hook.py:46} INFO - remote ready
[2022-10-30 06:00:10,242] {logging_mixin.py:115} INFO - re.compile('.*en formato csv*.')
[2022-10-30 06:00:10,248] {logging_mixin.py:115} INFO - []
[2022-10-30 06:00:10,339] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=etl_denue, task_id=get_files, execution_date=20220901T000000, start_date=20221030T060007, end_date=20221030T060010
[2022-10-30 06:00:10,380] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-30 06:00:10,404] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-30 08:15:34,990] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 08:15:34,996] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 08:15:34,996] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 08:15:34,996] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 08:15:34,996] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 08:15:35,004] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 08:15:35,017] {standard_task_runner.py:52} INFO - Started process 212 to run task
[2022-10-30 08:15:35,019] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmpqgiaj1h9', '--error-file', '/tmp/tmpzpm9g0xh']
[2022-10-30 08:15:35,020] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 08:15:35,055] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host f06c3fafa271
[2022-10-30 08:15:35,208] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 08:15:35,208] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 08:15:35,208] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 08:15:35,209] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 08:15:35,620] {selenium_hook.py:46} INFO - remote ready
[2022-10-30 08:15:48,995] {logging_mixin.py:115} INFO - ['/contenidos/masiva/denue/esenciales/Actividades_Economicas_Esenciales_csv.zip', '/contenidos/masiva/denue/esenciales/Actividades_Economicas_No_Esenciales_csv.zip', '/contenidos/masiva/denue/denue_00_23_csv.zip', '/contenidos/masiva/denue/denue_00_93_csv.zip', '/contenidos/masiva/denue/denue_00_11_csv.zip', '/contenidos/masiva/denue/denue_00_43_csv.zip', '/contenidos/masiva/denue/denue_00_46111_csv.zip', '/contenidos/masiva/denue/denue_00_46112-46311_csv.zip', '/contenidos/masiva/denue/denue_00_46321-46531_csv.zip', '/contenidos/masiva/denue/denue_00_46591-46911_csv.zip', '/contenidos/masiva/denue/denue_00_55_csv.zip', '/contenidos/masiva/denue/denue_00_51_csv.zip', '/contenidos/masiva/denue/denue_00_21_csv.zip', '/contenidos/masiva/denue/denue_00_31-33_csv.zip', '/contenidos/masiva/denue/denue_00_22_csv.zip', '/contenidos/masiva/denue/denue_00_81_1_csv.zip', '/contenidos/masiva/denue/denue_00_81_2_csv.zip', '/contenidos/masiva/denue/denue_00_72_1_csv.zip', '/contenidos/masiva/denue/denue_00_72_2_csv.zip', '/contenidos/masiva/denue/denue_00_56_csv.zip', '/contenidos/masiva/denue/denue_00_71_csv.zip', '/contenidos/masiva/denue/denue_00_62_csv.zip', '/contenidos/masiva/denue/denue_00_61_csv.zip', '/contenidos/masiva/denue/denue_00_52_csv.zip', '/contenidos/masiva/denue/denue_00_53_csv.zip', '/contenidos/masiva/denue/denue_00_54_csv.zip', '/contenidos/masiva/denue/denue_00_48-49_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_23_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_93_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_11_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_43_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_46111_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_46112-46311_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_46321-46531_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_46591-46911_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_55_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_51_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_21_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_31-33_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_22_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_81_1_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_81_2_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_72_1_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_72_2_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_56_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_71_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_62_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_61_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_52_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_53_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_54_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_48-49_1121_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_23_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_93_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_11_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_43_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_46111_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_46112-46311_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_46321-46531_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_46591-46911_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_55_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_51_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_21_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_31-33_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_22_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_81_1_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_81_2_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_72_1_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_72_2_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_56_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_71_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_62_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_61_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_52_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_53_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_54_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_48-49_0521_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_23_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_93_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_11_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_43_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_46111_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_46112-46311_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_46321-46531_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_46591-46911_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_55_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_51_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_21_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_31-33_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_22_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_81_1_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_81_2_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_72_1_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_72_2_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_56_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_71_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_62_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_61_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_52_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_53_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_54_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_48-49_1120_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_23_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_93_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_11_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_43_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_46111_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_46112-46311_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_46321-46531_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_46591-46911_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_55_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_51_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_21_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_31-33_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_22_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_81_1_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_81_2_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_72_1_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_72_2_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_56_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_71_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_62_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_61_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_52_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_53_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_54_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_48-49_0420_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_23_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_93_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_11_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_43_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_46111_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_46112-46311_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_46321-46531_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_46591-46911_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_55_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_51_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_21_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_31-33_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_22_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_81_1_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_81_2_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_72_1_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_72_2_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_56_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_71_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_62_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_61_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_52_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_53_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_54_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_48-49_1119_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_23_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_93_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_11_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_43_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_46111_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_46112-46311_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_46321-46531_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_46591-46911_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_55_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_51_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_21_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_31-33_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_22_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_81_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_72_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_56_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_71_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_62_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_61_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_52_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_53_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_54_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_48-49_0419_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_23_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_93_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_11_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_43_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_46111_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_46112-46311_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_46321-46531_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_46591-46911_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_55_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_51_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_21_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_31-33_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_22_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_81_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_72_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_56_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_71_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_62_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_61_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_52_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_53_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_54_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_48-49_1118_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_23_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_93_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_11_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_43_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_46111_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_46112-46311_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_46321-46531_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_46591-46911_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_55_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_51_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_21_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_31-33_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_22_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_81_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_72_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_56_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_71_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_62_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_61_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_52_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_53_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_54_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_48-49_0318_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_23_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_93_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_11_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_43_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_46111_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_46112-46311_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_46321-46531_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_46591-46911_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_55_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_51_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_21_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_31-33_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_22_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_81_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_72_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_56_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_71_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_62_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_61_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_52_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_53_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_54_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_48-49_1117_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_93_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_11_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_43_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_46111_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_23_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_55_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_22_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_31-33_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_51_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_21_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_81_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_72_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_56_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_71_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_62_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_61_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_52_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_53_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_54_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_48-49_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_46112-46311_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_46321-46531_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_46591-46911_0317_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_93_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_11_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_43_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_46111_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_23_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_55_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_22_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_31-33_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_51_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_21_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_81_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_72_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_56_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_71_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_62_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_61_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_52_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_53_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_54_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_48-49_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_46112-46311_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_46321-46531_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_46591-46911_1016_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_93_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_11_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_43_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_46111_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_23_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_55_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_22_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_31-33_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_51_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_21_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_81_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_72_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_56_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_71_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_62_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_61_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_52_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_53_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_54_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_48-49_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_46112-46311_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_46321-46531_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_46591-46911_0116_csv.zip', '/contenidos/masiva/denue/2015/denue_93_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_00_11_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_43_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_46111_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_00_23_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_55_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_00_22_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_31-33_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_51_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_00_21_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_81_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_72_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_56_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_71_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_62_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_61_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_52_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_53_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_54_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_48-49_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_46112-46311_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_46321-46531_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_46591-46911_25022015_csv.zip']
[2022-10-30 08:15:48,996] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/selenium_operator.py", line 24, in execute
    hook.run_script(self.script, self.script_args)
  File "/opt/airflow/plugins/hooks/selenium_hook.py", line 56, in run_script
    script(self.driver, *args)
  File "/opt/airflow/dags/utils/get_files.py", line 49, in selenium_scrapper
    file = requests.get(file_url, stream = True)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'www.inegi.org.mx/contenidos/masiva/denue/esenciales/Actividades_Economicas_Esenciales_csv.zip': No scheme supplied. Perhaps you meant http://www.inegi.org.mx/contenidos/masiva/denue/esenciales/Actividades_Economicas_Esenciales_csv.zip?
[2022-10-30 08:15:49,002] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_denue, task_id=get_files, execution_date=20220901T000000, start_date=20221030T081534, end_date=20221030T081549
[2022-10-30 08:15:49,009] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task get_files (Invalid URL 'www.inegi.org.mx/contenidos/masiva/denue/esenciales/Actividades_Economicas_Esenciales_csv.zip': No scheme supplied. Perhaps you meant http://www.inegi.org.mx/contenidos/masiva/denue/esenciales/Actividades_Economicas_Esenciales_csv.zip?; 212)
[2022-10-30 08:15:49,051] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-30 08:15:49,074] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-30 08:18:25,959] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 08:18:25,964] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 08:18:25,964] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 08:18:25,964] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-10-30 08:18:25,964] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 08:18:25,972] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 08:18:25,977] {standard_task_runner.py:52} INFO - Started process 221 to run task
[2022-10-30 08:18:25,979] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmp5x3qah_x', '--error-file', '/tmp/tmpcv_lz11b']
[2022-10-30 08:18:25,980] {standard_task_runner.py:80} INFO - Job 3: Subtask get_files
[2022-10-30 08:18:26,012] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host 123ff57f3405
[2022-10-30 08:18:26,153] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 08:18:26,154] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 08:18:26,154] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 08:18:26,154] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 08:18:26,469] {selenium_hook.py:46} INFO - remote ready
[2022-10-30 08:18:39,142] {logging_mixin.py:115} INFO - ['/contenidos/masiva/denue/esenciales/Actividades_Economicas_Esenciales_csv.zip', '/contenidos/masiva/denue/esenciales/Actividades_Economicas_No_Esenciales_csv.zip', '/contenidos/masiva/denue/denue_00_23_csv.zip', '/contenidos/masiva/denue/denue_00_93_csv.zip', '/contenidos/masiva/denue/denue_00_11_csv.zip', '/contenidos/masiva/denue/denue_00_43_csv.zip', '/contenidos/masiva/denue/denue_00_46111_csv.zip', '/contenidos/masiva/denue/denue_00_46112-46311_csv.zip', '/contenidos/masiva/denue/denue_00_46321-46531_csv.zip', '/contenidos/masiva/denue/denue_00_46591-46911_csv.zip', '/contenidos/masiva/denue/denue_00_55_csv.zip', '/contenidos/masiva/denue/denue_00_51_csv.zip', '/contenidos/masiva/denue/denue_00_21_csv.zip', '/contenidos/masiva/denue/denue_00_31-33_csv.zip', '/contenidos/masiva/denue/denue_00_22_csv.zip', '/contenidos/masiva/denue/denue_00_81_1_csv.zip', '/contenidos/masiva/denue/denue_00_81_2_csv.zip', '/contenidos/masiva/denue/denue_00_72_1_csv.zip', '/contenidos/masiva/denue/denue_00_72_2_csv.zip', '/contenidos/masiva/denue/denue_00_56_csv.zip', '/contenidos/masiva/denue/denue_00_71_csv.zip', '/contenidos/masiva/denue/denue_00_62_csv.zip', '/contenidos/masiva/denue/denue_00_61_csv.zip', '/contenidos/masiva/denue/denue_00_52_csv.zip', '/contenidos/masiva/denue/denue_00_53_csv.zip', '/contenidos/masiva/denue/denue_00_54_csv.zip', '/contenidos/masiva/denue/denue_00_48-49_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_23_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_93_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_11_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_43_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_46111_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_46112-46311_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_46321-46531_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_46591-46911_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_55_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_51_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_21_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_31-33_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_22_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_81_1_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_81_2_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_72_1_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_72_2_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_56_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_71_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_62_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_61_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_52_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_53_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_54_1121_csv.zip', '/contenidos/masiva/denue/2021_11/denue_00_48-49_1121_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_23_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_93_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_11_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_43_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_46111_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_46112-46311_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_46321-46531_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_46591-46911_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_55_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_51_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_21_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_31-33_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_22_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_81_1_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_81_2_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_72_1_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_72_2_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_56_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_71_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_62_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_61_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_52_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_53_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_54_0521_csv.zip', '/contenidos/masiva/denue/2021_05/denue_00_48-49_0521_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_23_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_93_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_11_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_43_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_46111_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_46112-46311_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_46321-46531_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_46591-46911_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_55_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_51_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_21_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_31-33_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_22_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_81_1_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_81_2_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_72_1_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_72_2_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_56_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_71_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_62_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_61_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_52_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_53_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_54_1120_csv.zip', '/contenidos/masiva/denue/2020_11/denue_00_48-49_1120_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_23_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_93_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_11_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_43_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_46111_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_46112-46311_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_46321-46531_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_46591-46911_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_55_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_51_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_21_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_31-33_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_22_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_81_1_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_81_2_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_72_1_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_72_2_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_56_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_71_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_62_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_61_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_52_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_53_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_54_0420_csv.zip', '/contenidos/masiva/denue/2020_04/denue_00_48-49_0420_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_23_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_93_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_11_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_43_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_46111_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_46112-46311_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_46321-46531_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_46591-46911_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_55_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_51_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_21_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_31-33_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_22_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_81_1_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_81_2_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_72_1_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_72_2_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_56_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_71_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_62_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_61_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_52_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_53_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_54_1119_csv.zip', '/contenidos/masiva/denue/2019_11/denue_00_48-49_1119_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_23_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_93_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_11_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_43_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_46111_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_46112-46311_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_46321-46531_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_46591-46911_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_55_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_51_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_21_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_31-33_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_22_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_81_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_72_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_56_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_71_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_62_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_61_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_52_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_53_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_54_0419_csv.zip', '/contenidos/masiva/denue/2019_04/denue_00_48-49_0419_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_23_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_93_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_11_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_43_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_46111_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_46112-46311_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_46321-46531_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_46591-46911_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_55_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_51_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_21_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_31-33_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_22_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_81_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_72_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_56_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_71_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_62_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_61_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_52_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_53_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_54_1118_csv.zip', '/contenidos/masiva/denue/2018_11/denue_00_48-49_1118_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_23_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_93_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_11_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_43_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_46111_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_46112-46311_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_46321-46531_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_46591-46911_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_55_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_51_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_21_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_31-33_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_22_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_81_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_72_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_56_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_71_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_62_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_61_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_52_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_53_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_54_0318_csv.zip', '/contenidos/masiva/denue/2018_03/denue_00_48-49_0318_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_23_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_93_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_11_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_43_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_46111_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_46112-46311_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_46321-46531_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_46591-46911_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_55_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_51_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_21_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_31-33_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_22_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_81_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_72_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_56_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_71_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_62_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_61_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_52_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_53_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_54_1117_csv.zip', '/contenidos/masiva/denue/2017_11/denue_00_48-49_1117_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_93_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_11_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_43_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_46111_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_23_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_55_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_22_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_31-33_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_51_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_21_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_81_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_72_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_56_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_71_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_62_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_61_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_52_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_53_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_54_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_48-49_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_46112-46311_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_46321-46531_0317_csv.zip', '/contenidos/masiva/denue/2017_03/denue_00_46591-46911_0317_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_93_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_11_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_43_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_46111_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_23_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_55_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_22_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_31-33_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_51_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_21_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_81_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_72_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_56_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_71_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_62_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_61_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_52_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_53_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_54_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_48-49_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_46112-46311_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_46321-46531_1016_csv.zip', '/contenidos/masiva/denue/2016_10/denue_00_46591-46911_1016_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_93_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_11_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_43_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_46111_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_23_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_55_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_22_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_31-33_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_51_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_21_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_81_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_72_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_56_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_71_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_62_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_61_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_52_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_53_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_54_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_48-49_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_46112-46311_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_46321-46531_0116_csv.zip', '/contenidos/masiva/denue/2016_01/denue_00_46591-46911_0116_csv.zip', '/contenidos/masiva/denue/2015/denue_93_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_00_11_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_43_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_46111_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_00_23_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_55_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_00_22_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_31-33_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_51_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_00_21_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_81_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_72_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_56_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_71_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_62_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_61_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_52_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_53_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_54_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_48-49_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_46112-46311_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_46321-46531_25022015_csv.zip', '/contenidos/masiva/denue/2015/denue_46591-46911_25022015_csv.zip']
[2022-10-30 08:21:17,271] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=etl_denue, task_id=get_files, execution_date=20220901T000000, start_date=20221030T081825, end_date=20221030T082117
[2022-10-30 08:21:17,308] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-30 08:21:17,325] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
