[2022-10-30 07:33:04,629] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 07:33:04,634] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 07:33:04,634] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 07:33:04,635] {taskinstance.py:1377} INFO - Starting attempt 16 of 21
[2022-10-30 07:33:04,635] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 07:33:04,642] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 07:33:04,649] {standard_task_runner.py:52} INFO - Started process 8129 to run task
[2022-10-30 07:33:04,651] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmp6hlrufpf', '--error-file', '/tmp/tmp64gxmppu']
[2022-10-30 07:33:04,652] {standard_task_runner.py:80} INFO - Job 18: Subtask get_files
[2022-10-30 07:33:04,689] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host 1dd15365b03f
[2022-10-30 07:33:04,733] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=16
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 07:33:04,832] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 07:33:04,832] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 07:33:04,832] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 07:33:04,923] {selenium_hook.py:46} INFO - remote ready
[2022-10-30 07:34:45,460] {logging_mixin.py:115} INFO - Message: 
Stacktrace:
#0 0x55a0c005c2c3 <unknown>
#1 0x55a0bfe6583a <unknown>
#2 0x55a0bfe9e985 <unknown>
#3 0x55a0bfe9eb61 <unknown>
#4 0x55a0bfed6d14 <unknown>
#5 0x55a0bfebcf6d <unknown>
#6 0x55a0bfed4a50 <unknown>
#7 0x55a0bfebcd63 <unknown>
#8 0x55a0bfe917e3 <unknown>
#9 0x55a0bfe92a21 <unknown>
#10 0x55a0c00aa18e <unknown>
#11 0x55a0c00ad622 <unknown>
#12 0x55a0c0090aae <unknown>
#13 0x55a0c00ae2a3 <unknown>
#14 0x55a0c0084ecf <unknown>
#15 0x55a0c00ce588 <unknown>
#16 0x55a0c00ce706 <unknown>
#17 0x55a0c00e88b2 <unknown>
#18 0x7f6dcfa0e609 <unknown>
[2022-10-30 07:34:45,533] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/selenium_operator.py", line 24, in execute
    hook.run_script(self.script, self.script_args)
  File "/opt/airflow/plugins/hooks/selenium_hook.py", line 56, in run_script
    script(self.driver, *args)
  File "/opt/airflow/dags/utils/get_files.py", line 36, in selenium_scrapper
    soup = BeautifulSoup(innerHTML, 'html.parser')
UnboundLocalError: local variable 'innerHTML' referenced before assignment
[2022-10-30 07:34:45,539] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_denue, task_id=get_files, execution_date=20220901T000000, start_date=20221030T073304, end_date=20221030T073445
[2022-10-30 07:34:45,546] {standard_task_runner.py:97} ERROR - Failed to execute job 18 for task get_files (local variable 'innerHTML' referenced before assignment; 8129)
[2022-10-30 07:34:45,567] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-30 07:34:45,587] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
